####################################################################################################
# TEMPLATE FOR ALL DOCKER-RELATED JOBS
####################################################################################################

.docker:
  image: docker:stable
  stage: deploy
  tags:
    - dockerd
  # only run when the IMAGE variable exists and is not null
  only:
    variables:
      - $IMAGE
  before_script:
    - docker -v
    - echo ${IMAGE}
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    # set the tag for the image we're building from (defaults to latest)
    - if [ -z "${FROM_TAG}" ]; then export FROM_TAG=latest; else echo ${FROM_TAG}; fi
  after_script:
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep ${IMAGE})

####################################################################################################
# TEMPLATE FOR MASTER-ONLY DOCKER-RELATED JOBS
####################################################################################################

.docker-edge:
  extends: .docker
  # matches only on the master branch
  only:
    refs:
      - master
  variables:
    COMMIT: ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    EDGE: ${IMAGE}:edge
  script:
    - docker build --build-arg from_tag=${FROM_TAG} -t ${COMMIT} -t ${EDGE} .
    - docker push ${COMMIT} && docker push ${EDGE}

####################################################################################################
# TEMPLATE FOR BRANCH-ONLY DOCKER-RELATED JOBS
####################################################################################################

.docker-branch:
  extends: .docker
  # matches only on non-master branches
  only:
    refs:
      - branches
  except:
    refs:
      - master
  variables:
    COMMIT: ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    BRANCH: ${IMAGE}:${CI_COMMIT_REF_SLUG}
  script:
    - docker build --build-arg from_tag=${FROM_TAG} -t ${COMMIT} -t ${BRANCH} .
    - docker push ${COMMIT} && docker push ${BRANCH}

####################################################################################################
# TEMPLATE FOR RELEASE-ONLY DOCKER-RELATED JOBS
####################################################################################################

.docker-stable:
  extends: .docker
  # matches only on tags of the form vX.Y.Z
  only:
    refs:
      - /^v(\d+\.)?(\d+\.)?(\d+)$/
  except:
    refs:
      - branches
  variables:
    LATEST: ${IMAGE}:latest
    STABLE: ${IMAGE}:stable
  script:
    # grab the version number from the VERSION.txt file
    - if [ ! -f VERSION.txt ]; then return 1; else eval VERSION=$(cat VERSION.txt); fi
    # make sure tag matches VERSION.txt (disabled for now)
    - if [ "${CI_COMMIT_TAG}" = "v${VERSION}" ]; then RELEASE=${IMAGE}:${VERSION}; else return 1; fi
    # drop the "v" from the tag when tagging Docker images
    - docker build --build-arg from_tag=${FROM_TAG} -t ${RELEASE} -t ${STABLE} -t ${LATEST} .
    - docker push ${RELEASE} && docker push ${STABLE} && docker push ${LATEST}
